### ISSUE TITLE
Console log warning keeps coming up

### ISSUE THREAD

**Issue by djamaile** [antvis/Graphin#101]
**Describe the bug**
When using the examples provided on the site, this warning keeps getting logged: "The layout method: [object Object] does not exist! Please specify it first. ".

**To Reproduce**
https://codesandbox.io/s/ecstatic-rgb-qef3h?file=/index.jsx

**Expected behavior**
Layout force method exists so this warning should not be fired off. It can be that I am misunderstanding it, as docs are not in english.  

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser chrome
 - Version 81.0.4044.129

**Comment by Anderson-Liu** [comment]
I think this is because @antv/graphin:latest(now is 1.2.0) use "@antv/g6": "~3.2.3"(you can check [here](https://github.com/antvis/Graphin/blob/master/packages/graphin/package.json#L44) ).

In "@antv/g6": "~3.2.3", it used to have a bug fix [here](https://github.com/antvis/G6/commit/301d5125a42065826747a5fab913e7193e534f19#diff-a894326c4bf99073031085098f94dac8L168-R178) , which add additional check to avoid null value access. 

![image](https://user-images.githubusercontent.com/8468372/81265581-ec677d00-9075-11ea-9f53-625bd159fd5b.png)

So, maybe it should be upgrade dependency lib @antv/g6 to the latest version, and release  a new version of @antv/graphin. @pomelo-nwu 

On the other hand, I still can' t figure out why `this.layoutType == undefined` will be `true` . This may need the author to do more analysis.

**Comment by tolulope-od** [comment]
I am also facing the same issue @djamaile is facing, I keep getting console warnings even though I have set the layout options. Any fix for this?
