### ISSUE TITLE
(TypeError: Cannot set property 'originAttrs' of null) when updating Graphin's data prop quickly

### ISSUE THREAD

**Issue by peironggg** [antvis/Graphin#133]
<img width="1278" alt="Screenshot 2020-05-22 at 3 01 41 PM" src="https://user-images.githubusercontent.com/35712975/82642204-23c25600-9c40-11ea-8f0a-2c2d4550f1d6.png">

When the Graphin component is rendered with a new data object (passed into the data prop), the webapp will crash with this error (above). The Graphin component is rendered when I drag a scale (show in the .gif below), causing many renders to be fired off and subsequently the error to occur. If you have an idea of what the cause may be (For example, each render is causing another process to be running in the background that needs to set 'originAttrs' which disappears when the data prop changes), do let me know! Any help is appreciated. 谢谢 :)

![Recording](https://user-images.githubusercontent.com/35712975/82642100-fa092f00-9c3f-11ea-8036-d24b8106eaf2.gif)

**Comment by pomelo-nwu** [comment]
Can you put the above example in [codesandbox](https://codesandbox.io/) for me so that I can reproduce the problem locally. I guess you need to do a timing analysis, you can join the group to discuss （DingTalk）, so that the problem can be solved faster than the ISSUE
![image](https://user-images.githubusercontent.com/10703060/82723724-829cd380-9d03-11ea-9bc2-35f0804893c2.png)

**Comment by pomelo-nwu** [comment]
![image](https://user-images.githubusercontent.com/10703060/84900814-32841780-b0dd-11ea-9448-cbeef9f56ac4.png)

done
