### ISSUE TITLE
Not showing the SVG to the graph Node.

### ISSUE THREAD

**Issue by Wathsara** [antvis/Graphin#204]
I have tried to add a custom marker to the node but it didn't change anything in the graph. I have tried the code you have given as well, https://codesandbox.io/s/xy4zy still couldn't solve my issue.

**Comment by pomelo-nwu** [comment]
The svg-marker method has been removed in the graphin1.x version, because `svg2Marker` has some weird bugs.The document has not been updated in time, sorry for the confusion.
It is recommended that you use the graphin 2.x version and use font as the node icon. [Details can be viewed](https://antv.vision/graphin-docs/graphin/render/node#02%E8%AE%BE%E7%BD%AE%E5%AD%97%E4%BD%93%E5% 9B%BE%E6%A0%87) Internationalization documents are still in preparation.

**Comment by pomelo-nwu** [comment]
@Wathsara https://graphin.antv.vision/en-US/graphin/render/demos
