### ISSUE TITLE
afterlayout Event is not is not firing

### ISSUE THREAD

**Issue by logeekal** [antvis/Graphin#99]
**Describe the bug**
afterlayout event is not getting triggered.

**To Reproduce**

https://codesandbox.io/s/after-layout-event-not-fired-opstr

**Expected behavior**
In console, Both "After Layout" and "Before Layout"  should printed.  But it is only printing Before Layout.

![image](https://user-images.githubusercontent.com/7485038/80483508-d66e0400-8973-11ea-8a1d-100a68397629.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - NA
 - Browser [e.g. chrome, safari] - NA
 - Version [e.g. 22] - NA

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - NA
 - OS: [e.g. iOS8.1]- NA
 - Browser [e.g. stock browser, safari] - NA

**Additional context**

**Comment by logeekal** [comment]
Did anybody got a chance to look at this please?

**Comment by pomelo-nwu** [comment]
> Did anybody got a chance to look at this please?

I'm sorry to reply you a bit late . because of some historical reasons, graphin's layout process does not adopt the G6 layout method. Therefore, the G6 `afterlayout` and` beforelayout` hook functions will only be triggered when they pass [options.layout](https://g6.antv.vision/zh/docs/api/Graph#layout). In order to maintain backward compatibility, Graphin also retained this method. If you want to set the layout by props.layout, you can use the [afterchangedata](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/Graphin.tsx#L244), which will be rendered immediately after the layout inside the graphin.

**Comment by pomelo-nwu** [comment]
https://codesandbox.io/s/g6options-after-layout-event-not-fired-gmwco?file=/src/Graph.tsx

**Comment by pomelo-nwu** [comment]
@logeekal graphin2.0 布局机制和G6保持一致：https://github.com/antvis/Graphin/blob/master/packages/graphin/src/layout/index.ts#L42
